spring:
  thymeleaf:
    cache: false
  mail:
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
  #??  jpa.open-in-view: false
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:db
   # url: jdbc:h2:file:C:/gosia/development/budget/db
    url: ${DB_URL:jdbc:hsqldb:file:db/budget}
    username: ${DB_USER:SA}
    password: ${DB_PASS:}
  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  flyway:
    enabled: true
    baselineOnMigrate: ${DB.FIRST_TIME:false}
    locations: classpath:db/migration
budget.path: ${DB_URL:value}
aspect.enabled: false
deposit.reminder.days: 7
logging:
  level:
#    org.hibernate.SQL: DEBUG
    mza:
      thy: DEBUG
