spring:
#??  jpa.open-in-view: false
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:db
   # url: jdbc:h2:file:C:/gosia/development/budget/db
    url: ${MZA.PATH:jdbc:hsqldb:file:db/budget}
    username: SA
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
budget.path: ${MZA.VAR:value}
logging:
  level:
    org.hibernate.SQL: DEBUG
    mza:
      thy: DEBUG