spring:
  datasource:
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:db
    url: jdbc:h2:file:C:/gosia/development/budget/db
    username: sa
    password: sa
  jpa:
    show-sql=true:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration

logging:
  level:
    com:
      thy: DEBUG